Refactored to be compatible with new snmpd-connector-lib.

diff --git a/usr/sbin/snmpd-mdraid-connector b/usr/sbin/snmpd-mdraid-connector
--- a/usr/sbin/snmpd-mdraid-connector
+++ b/usr/sbin/snmpd-mdraid-connector
@@ -1,41 +1,43 @@
 #!/bin/bash -u
 
+# Include snmpd-connector-lib.sh or die.
 [[ ! -r /usr/lib/snmpd-connector-lib.sh ]] && echo "Unable to find /usr/lib/snmpd-connector-lib.sh" && exit 1
 source /usr/lib/snmpd-connector-lib.sh
 
-function send_index
+# Helper function to get the device path from the devices array using a 1 based index
+#
+#	@in_param	$1 - The 1 based index of the device
+#	@out_param	$2 - The path of this device
+#
+function get_device_path
 {
-	# If the index is in range...
-	if (( ${RINDEX} <= ${#DEVICES[@]} )); then
-		# Send the OID and the index number.
-		send_integer ${OID} ${RINDEX}
-	else
-		# Send none.
-		echo "NONE"
-	fi
+	local AINDEX=$((${1} - 1))
+	eval $2=${DEVICES[${AINDEX}]}	
 }
 
 # Helper function to make the filename for a device.
 #
-#	@param	$1 - The DEVICE to create a path for
-#	@return	$2 - The device cache file path
+#	@in_param	$1 - The 1 based index of the device
+#	@out_param	$2 - The device cache file path
 #
 function get_device_filename
 {
-	local DEVFNAME
+	local DEVPATH DEVFILE
 	
-	# Make the device info filename 
-	DEVFNAME=${1##\/}
-	DEVFNAME=${CACHEDIR}/${DEVFNAME//\//_}_mdinfo
+	# Make the device info filename
+	get_device_path ${1} DEVPATH
 	
-	eval $2=${DEVFNAME}
+	DEVFILE=${DEVPATH##\/}
+	DEVFILE=${CACHEDIR}/${DEVFILE//\//_}_mdinfo
+	
+	eval $2=${DEVFILE}
 }
 
 # Helper function to get the string value of a field
 #
-#	@param	$1 - The DEVICE to get info for
-#	@param	$2 - The search string
-#	@return	$3 - The string we found, if any.
+#	@in_param	$1 - The 1 based index of the device
+#	@in_param	$2 - The search string
+#	@out_param	$3 - The string we found, if any.
 #
 function get_field
 {
@@ -59,24 +61,56 @@ function get_field
 	eval $3="N/A" 
 }
 
+# Function to send the index value
+#
+#	@in_param	$1 - The OID to send before this data
+#	@in_param	$2 - The index value
+#
+function send_index
+{
+	# If the index is in range...
+	if (( $# > 1 )); then
+		if (( ${2} <= ${#DEVICES[@]} )); then
+			# Send the OID and the index number.
+			send_integer ${1} ${2}
+			return
+		fi
+	fi
+
+	# Send the OID and NONE.
+	send_none ${1}
+}
+
+# Function to send the device path
+#
+#	@in_param	$1 - The OID to send before this data
+#	@in_param	$2 - The index value
+#
+function send_device_path
+{
+	local DEVPATH 
+	get_device_path ${2} DEVPATH
+	send_string ${1} ${DEVPATH}
+}
+
 # Function to send array info (string) - called: send_device_info_str OID DEVICE "Info String"
 #
-#	$1 - The OID to send before this data
-#	$2 - The DEVICE to send data for
-#	$3 - The STRING to search for
+#	@in_param	$1 - The STRING to search for
+#	@in_param	$2 - The OID to send before this data
+#	@in_param	$3 - The index value
 #
 function send_device_info_str
 {
 	local VALUE
 	
-	get_field ${2} "${3}" VALUE
-	send_string ${1} ${VALUE}
+	get_field ${3} "${1}" VALUE
+	send_string ${2} ${VALUE}
 }
 
 # Function to send array health (string) - called: send_device_health OID DEVICE
 #
-#	$1 - The OID to send before this data
-#	$2 - The DEVICE to send data for
+#	@in_param	$1 - The OID to send before this data
+#	@in_param	$2 - The index value
 #
 function send_device_health
 {
@@ -88,8 +122,8 @@ function send_device_health
 
 # Function to boolean indicating array has failed components - called: send_device_has_failed OID DEVICE
 #
-#	$1 - The OID to send before this data
-#	$2 - The DEVICE to send data for
+#	@in_param	$1 - The OID to send before this data
+#	@in_param	$2 - The index value
 #
 function send_device_has_failed
 {
@@ -101,8 +135,8 @@ function send_device_has_failed
 
 # Function to boolean indicating array has available spares - called: send_device_has_spares OID DEVICE
 #
-#	$1 - The OID to send before this data
-#	$2 - The DEVICE to send data for
+#	@in_param	$1 - The OID to send before this data
+#	@in_param	$2 - The index value
 #
 function send_device_has_spares
 {
@@ -117,77 +151,107 @@ function send_device_has_spares
 #	$1 - The OID to send before this data
 #	$2 - The DEVICE to send data for
 #	$3 - The STRING to search for
+#	@in_param	$1 - The STRING to search for
+#	@in_param	$2 - The OID to send before this data
+#	@in_param	$3 - The index value
 #
 function send_device_info_gauge
 {
 	local VALUE
 	
-	get_field ${2} "${3}" VALUE
-	send_gauge ${1} ${VALUE}
+	get_field ${3} "${1}" VALUE
+	send_gauge ${2} ${VALUE}
+}
+
+# Function to get the next index value
+#
+#	@in_param	$2 - The base OID this is a request for
+#	@in_param	$+ - An array containing the request elements
+#
+function get_next_index
+{
+	local RETVAL
+	
+	debug_function_enter "get_next_index" ${@}
+	
+	# If we still have more than one element in the request array then something
+	# is wrong so log an error and return 0.
+	if (( $# > 2 )); then
+		error_echo "get_next_index: called with $(( $# - 1 )) request array elements!"
+		debug_function_return 0
+		return 0
+	fi
+
+	# If we passed an index...
+	if (( $# > 1 )); then
+		# If the passed index is less than the number of devices then return it +1,
+		# otherwise return 0 to indicate that the index would be out of range. 
+		if (( ${2} < ${#DEVICES[@]} )); then
+			RETVAL=$(( ${2} + 1 ))
+			debug_echo "next index is in range, returning ${RETVAL}"
+			debug_function_return ${RETVAL}
+			return ${RETVAL}
+		else
+			debug_echo "next index would be out of range, returning zero"
+			debug_function_return 0
+			return 0
+		fi 
+	fi	
+	
+	# If we got this far then we were not passed an index so return the first
+	# available index.
+	debug_echo "no index supplied, returning first index"
+	debug_function_return 1
+	return 1
 }
 
 # Init local vars
-CMDNAME=$(basename ${0})
+CMDNAME="$(basename ${0})"
 CONFIG="/etc/snmpd-mdraid-connector"
 DEBUG=""
+LOGGING=""
 DEVICES=""
 CACHEDIR=""
 SNMP_TRANSLATE=""
 
 # Read the config file if we can
-[[ -r ${CONFIG} ]] && source ${CONFIG} || die "Unable to read configuration file [${CONFIG}]"
+[[ -r "${CONFIG}" ]] && source ${CONFIG} || die "Unable to read configuration file [${CONFIG}]"
 
 # Check for config values.
-[[ -z ${DEVICES} ]] && die "No DEVICES configured in ${CONFIG}"
-[[ -z ${CACHEDIR} ]] && die "No CACHEDIR configured in ${CONFIG}"
-[[ ! -d ${CACHEDIR} ]] && die "Cache directory [${CACHEDIR}] is not a directory"
-[[ ! -w ${CACHEDIR} ]] && die "Cache directory [${CACHEDIR}] is not writable by $(whoami)"
-[[ -z ${SNMP_TRANSLATE} ]] && die "No SNMP_TRANSLATE command configured in ${CONFIG}"
+[[ -z "${DEVICES}" ]] && die "No DEVICES configured in ${CONFIG}"
+[[ -z "${CACHEDIR}" ]] && die "No CACHEDIR configured in ${CONFIG}"
+[[ ! -d "${CACHEDIR}" ]] && die "Cache directory [${CACHEDIR}] is not a directory"
+[[ ! -r "${CACHEDIR}" ]] && die "Cache directory [${CACHEDIR}] is not readable by $(whoami)"
+[[ -z "${SNMP_TRANSLATE}" ]] && die "No SNMP_TRANSLATE command configured in ${CONFIG}"
 
-# Get base OID
-BASE_MIB="MD-RAID-MIB::mdRaidTable"
-BASE_OID="$(${SNMP_TRANSLATE} -On ${BASE_MIB}).1."
-(( $? != 0 )) && die "Unable to resolve base OID from ${BASE_MIB}"
+# Configure base address
+BASE_MIB="MD-RAID-MIB::mdRaid"
+
+# Declare the root table
+RTABLE[2]="#ETABLE"
+
+# Declare the E[ntry]TABLE
+ETABLE[1]="#FTABLE"
 
 # Declare the function table.
-FTABLE[1]="send_index"											# It is an index request.
-FTABLE[2]="send_string %o %d" 									# It is for the mapped device path.
-FTABLE[3]="send_device_info_str %o %d 'Version'" 				# It is for the raid version.
-FTABLE[4]="send_device_info_str %o %d 'UUID'" 					# It is for the raid UUID.
-FTABLE[5]="send_device_info_str %o %d 'Raid Level'"				# It is for the raid level.
-FTABLE[6]="send_device_info_str %o %d 'Layout'" 				# It is for the raid layout.
-FTABLE[7]="send_device_info_str %o %d 'Chunk Size'"				# It is for the raid chunk size.
-FTABLE[8]="send_device_info_str %o %d 'Array Size'" 			# It is for the raid array size.
-FTABLE[9]="send_device_info_str %o %d 'Used Dev Size'"			# It is for the raid used device size.
-FTABLE[10]="send_device_health %o %d"							# It is for the overall array health state.
-FTABLE[11]="send_device_has_failed %o %d"						# Boolean indicating failed components.
-FTABLE[12]="send_device_has_spares %o %d"						# Boolean indicating available spares.
-FTABLE[13]="send_device_info_gauge %o %d 'Total Devices'"		# It is for the total number of devices in the array.
-FTABLE[14]="send_device_info_gauge %o %d 'Active Devices'"		# It is for the number of active devices in the array.
-FTABLE[15]="send_device_info_gauge %o %d 'Working Devices'"		# It is for the number of working devices in the array.
-FTABLE[16]="send_device_info_gauge %o %d 'Failed Devices'"		# It is for the number of failed devices in the array.
-FTABLE[17]="send_device_info_gauge %o %d 'Spare Devices'"		# It is for the number of spare devices in the array.
-
-# Define the function to perform string replacement
-#
-#	@param	$1 - The starting string
-#	@param	$2 - The R[equest]TYPE
-#	@param	$3 - The R[equest]INDEX
-#	@return	$4 - The resulting string
-#
-# 	%o does not require handling
-#
-function do_string_replace
-{
-	local TEMP="${1}"
-	local AINDEX=$((${3} - 1))
-
-	# Replace %d with the device path		
-	TEMP="${TEMP/\%d/${DEVICES[${AINDEX}]}}"
-	
-	eval $4="\"${TEMP}\""
-}
+FTABLE[0]="get_next_index"								# Internal function to get next index
+FTABLE[1]="send_index"									# It is an index request.
+FTABLE[2]="send_device_path" 							# It is for the mapped device path.
+FTABLE[3]="send_device_info_str 'Version'" 				# It is for the raid version.
+FTABLE[4]="send_device_info_str 'UUID'" 				# It is for the raid UUID.
+FTABLE[5]="send_device_info_str 'Raid Level'"			# It is for the raid level.
+FTABLE[6]="send_device_info_str 'Layout'" 				# It is for the raid layout.
+FTABLE[7]="send_device_info_str 'Chunk Size'"			# It is for the raid chunk size.
+FTABLE[8]="send_device_info_str 'Array Size'" 			# It is for the raid array size.
+FTABLE[9]="send_device_info_str 'Used Dev Size'"		# It is for the raid used device size.
+FTABLE[10]="send_device_health"							# It is for the overall array health state.
+FTABLE[11]="send_device_has_failed"						# Boolean indicating failed components.
+FTABLE[12]="send_device_has_spares"						# Boolean indicating available spares.
+FTABLE[13]="send_device_info_gauge 'Total Devices'"		# It is for the total number of devices in the array.
+FTABLE[14]="send_device_info_gauge 'Active Devices'"	# It is for the number of active devices in the array.
+FTABLE[15]="send_device_info_gauge 'Working Devices'"	# It is for the number of working devices in the array.
+FTABLE[16]="send_device_info_gauge 'Failed Devices'"	# It is for the number of failed devices in the array.
+FTABLE[17]="send_device_info_gauge 'Spare Devices'"		# It is for the number of spare devices in the array.
 
 # Start the loop
 the_loop
-
